module: fl
model_name: cnn
models:
  transformers:
    vocab_size: 98635
    num_classes: 62
    embadding_dim: 32
    token_max_len: 200
    head_num: 8
    nlayers: 2
    batch_size: 16
  cnn:
    num_classes: 10
    dim: 1024
    batch_size: 15
num_clients: 50
epochs: 30
learning_rate: 0.001
dataset: emnist
agnews:
  max_len: 200
  niid: true
  partition: dirichlet
  balance: false
emnist:
  niid: true
  partition: dirichlet
  balance: true
device: gpu
device_id: 0
join_ratio: 0.5
client_drop_rate: 0.2
global_rounds: 1
time_threthold: 10000
algorithm: lsh_cold_start
save_dir: results/
random_clients_selected: false
eval_gap: 1
random_seed: 886
fedAlgorithm:
  lsh:
    data_volume: 500
    mu: 0.2
    per_local_steps: 2
    num_rounds: 10
    dlg_eval: False
    dlg_gap: 100
new_clients:
  rate: 0.5
  started_round: 20
  num_join_each_round: 5
  enabled: true