module: fl
model_name: cnn
models:
  transformers:
    vocab_size: 98635
    num_classes: 10
    embadding_dim: 32
    token_max_len: 200
    head_num: 8
    nlayers: 2
    batch_size: 15
  cnn:
    num_classes: 10
    dim: 1024
    batch_size: 15
num_clients: 25
epochs: 5
learning_rate: 0.005
dataset: mnist
agnews:
  max_len: 200
  niid: true
  partition: dirichlet
  balance: false
mnist:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
device: gpu
device_id: 0
join_ratio: 0.5
client_drop_rate: 0.2
global_rounds: 6
time_threthold: 10000
algorithm: fedsoft
save_dir: results/
random_clients_selected: false
eval_gap: 1
random_seed: 777
fine_tuning_epoch: 5
fedAlgorithm:
  fedsoft:
    estimate_samples: 256
    count_smoother: 0.0001
    estimation_interval: 4
new_clients:
  rate: 0.2
  started_round: 3
  num_join_each_round: 5
  enabled: true
cluster:
  cluster_num: 10