module: scaffold
model_name: cnn
models:
  transformers:
    vocab_size: 98635
    num_classes: 10
    embadding_dim: 32
    token_max_len: 200
    head_num: 8
    nlayers: 2
    batch_size: 10
  cnn:
    num_classes: 10
    dim: 1024
    batch_size: 15
num_clients: 25
epochs: 1
learning_rate: 0.005
dataset: mnist
agnews:
  max_len: 200
  niid: true
  partition: dirichlet
  balance: false
mnist:
  niid: true
  partition: dirichlet
  balance: true
device: gpu
device_id: 0
join_ratio: 0.5
client_drop_rate: 0.0
global_rounds: 10
time_threthold: 10000
algorithm: scaffold
save_dir: results/
random_clients_selected: false
eval_gap: 1
random_seed: 777
fine_tuning_epoch: 5
fedAlgorithm:
  scaffold:
    server_learning_rate: 1.0
new_clients:
  rate: 0.2
  started_round: 3
  num_join_each_round: 5
  enabled: false
cluster:
  cluster_num: 10
  auto: True
  start_to_cluster: 20
