# model settings
module: fl
model_name: clip
is_multimodal: True
multimodal:
  creamfl:
    text: textencoder
    image: resnet18
    multimodal: pcme
models:
  NormTextImageClassifier:
    img_dim: 1280
    text_dim: 768
  densenetbert:
    img_dim: 1280
    text_dim: 768
  pcme:
    embedding_dim: 256
    n_samples_inference: 7
    not_bert: true
    cnn_type: resnet18
    mlp_local: false
    word_dim: 300
  scanpp:
    embedding_dim: 512
  clip:
    pretrained: True
    partial: True
  # pretrained_clip:

# server settings
num_clients: 50
epochs: 3
learning_rate: 0.005
join_ratio: 0.2
client_drop_rate: 0.1
global_rounds: 300
# global_rounds: 8
eval_gap: 4
random_seeds: 777

# client settings
device: gpu
device_id: 0
time_threthold: 10000
algorithm: mmic
save_dir: results/
random_clients_selected: false
random_seed: 777
fine_tuning_epoch: 5
client_settings:
  text: 10
  image: 10
  multimodal: 15

# dataset 
dataset: food101
food101:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.5
  num_classes: 101
  batch_size: 5
  data_dir: repository/food101/
  missing_modal_rate: 0.5
  missing_modal_clients_rate: 0.5
  is_preload: false
crisis_mmd:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.5
  num_classes: 8
  batch_size: 15
  data_dir: repository/crisis_mmd/
  missing_modal_rate: 0.5
  missing_modal_clients_rate: 0.5
  is_preload: true
creamfl:
  server: coco
  text: agnews
  image: cifar10
  multimodal: flickr30k
agnews:
  max_len: 300
  niid: true
  partition: dirichlet
  balance: false
  num_classes: 4
  alpha: 0.1
  batch_size: 15
mnist:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  num_classes: 10
  batch_size: 15
cifar10:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  num_classes: 10
  batch_size: 15
flickr30k:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  batch_size: 15
  data_dir: repository/flickr30k
  missing_modal_rate: 0.2
  missing_modal_clients_rate: 0.3
  
coco:
  batch_size: 15

# algorithm settings
fedAlgorithm:
  ofchp:
    data_volume: 100
    hash_num: 12
    cv_dim: 1280
    budget: 20
    alpha: 10.0
    linkage: average
  fedsoft:
    estimate_samples: 256
    count_smoother: 0.0001
    estimation_interval: 4
  creamfl:
    is_inter_constrast: true
    is_intra_constrast: true
    kd_weight: 0.3
    inter_intra_weight: 0.5
    disabled_distill: false
    not_bert: true
    
new_clients:
  rate: 0.2
  started_round: 3
  num_join_each_round: 5
  enabled: false
cluster:
  cluster_num: 8
  cluster_test_subrate: 0.25

global_test_subrate: 0.3
training_subset_rate: 0.2
banzhaf_selected_rounds: 100
is_gen_modality: false
poverty_check: false