# model settings
module: fl
model_name: scanpp
is_multimodal: True
multimodal:
  creamfl:
    text: textencoder
    image: resnet18
    multimodal: pcme
models:
  NormTextImageClassifier:
    img_dim: 1280
    text_dim: 768
  densenetbert:
    img_dim: 1280
    text_dim: 768
  pcme:
    embedding_dim: 256
    n_samples_inference: 7
    not_bert: true
    cnn_type: resnet18
    mlp_local: false
    word_dim: 300
  scanpp:
    embedding_dim: 512

# server settings
num_clients: 50
epochs: 3
learning_rate: 0.005
join_ratio: 0.5
client_drop_rate: 0.1
global_rounds: 300
eval_gap: 4
random_seeds: 777
q
  multimodal: flickr30k
agnews:
  max_len: 300
  niid: true
  partition: dirichlet
  balance: false
  num_classes: 4
  alpha: 0.1
  batch_size: 15
mnist:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  num_classes: 10
  batch_size: 15
cifar10:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  num_classes: 10
  batch_size: 15
flickr30k:
  niid: true
  partition: dirichlet
  balance: true
  alpha: 0.1
  batch_size: 15
  data_dir: repository/flickr30k
  missing_modal_rate: 0.2
  missing_modal_clients_rate: 0.3
  
coco:
  batch_size: 15

# algorithm settings
fedAlgorithm:
  ofchp:
    data_volume: 300
    hash_num: 12
    cv_dim: 1280
  fedsoft:
    estimate_samples: 256
    count_smoother: 0.0001
    estimation_interval: 4
  creamfl:
    is_inter_constrast: true
    is_intra_constrast: true
    kd_weight: 0.3
    inter_intra_weight: 0.5
    disabled_distill: false
    not_bert: true
    
new_clients:
  rate: 0.2
  started_round: 3
  num_join_each_round: 5
  enabled: false
cluster:
  cluster_num: 4

training_subset_rate: 0.4
banzhaf_selected_rounds: 400